### ISSUE TITLE
O compartilhamento está trazendo o link do app, não das notícias

### ISSUE THREAD

**Issue by pabloklein** [CovidZero/covidzero-frontend#111]

**Comment by pabloklein** [comment]
<img width="1709" alt="Screenshot 2020-03-30 at 10 46 40" src="https://user-images.githubusercontent.com/50836724/77898882-c3ccb600-7273-11ea-9c73-e049ab82d551.png">

**Comment by lParanhos** [comment]
https://github.com/CovidZero/covidzero-frontend/pull/116
