### ISSUE TITLE
Define map lib

### ISSUE THREAD

**Issue by sergiodanilo** [CovidZero/covidzero-frontend#15]
Precisamos ver qual lib pode ser mais útil em nossa aplicação

**Comment by CarlosDanielDev** [comment]
Estou dando uma olhada em como funciona o Leaftlet, caso eu não tenha muito sucesso, a sugestão seria conseguir uma API key pra utilizar os serviços do Google Maps.

**Comment by VictorAlessander** [comment]
Leaflet é uma boa. Estou implementando em uma ferramenta do meu atual emprego e particularmente estou achando simples.

**Comment by Ualas** [comment]
O @pablopreme conseguiu a do Google Maps, então acho que vamos prosseguir com a lib deles.
