### ISSUE TITLE
Adjust NavBar (Mobile)

### ISSUE THREAD

**Issue by sergiodanilo** [CovidZero/covidzero-frontend#26]
1. Add icons (style guides);
2. Decrease font size
3. Decrease navbar height 
4. Change Map label to Brasil

<img width="420" alt="Screenshot 2020-03-24 at 12 07 21" src="https://user-images.githubusercontent.com/664727/77423872-0e5bb780-6dc8-11ea-816a-7ba3d43fd0c4.png">

**Comment by fredericodib** [comment]
vou fazer esse

**Comment by fredericodib** [comment]
feito
