### ISSUE TITLE
Suggestion: support TypeScript

### ISSUE THREAD

**Issue by vcapretz** [CovidZero/covidzero-frontend#4]
Hey, just stumbled on the project, nice initiative! 

Have you considered TypeScript for the project? As it's still early on it may be easier to set up and then just maintain support over time, I could open a PR with the setup allowing JS files in parallel.

Let me know your thoughts 😄

**Comment by VictorHaine** [comment]
Hi Vitor, as we started as quick as possible we didn't have time to discuss TypeScript.

@pablopreme What do you think?

**Comment by VictorHaine** [comment]
Hi Vitor, as we started as quickly as possible we didn't have time to discuss TypeScript.

@pablopreme What do you think?
