### ISSUE TITLE
Adjust header height

### ISSUE THREAD

**Issue by sergiodanilo** [CovidZero/covidzero-frontend#54]
![header](https://user-images.githubusercontent.com/664727/77353479-f25d0500-6d38-11ea-89d1-7526ec16a823.PNG)

**Comment by Fred-Reis** [comment]
Issue finalizada 
![Captura de Tela 2020-03-23 às 16 31 50](https://user-images.githubusercontent.com/52092659/77355765-d00cbc80-6d23-11ea-8654-026c230376c7.png)
