### ISSUE TITLE
Corrigir o bottom das páginas

### ISSUE THREAD

**Issue by Qnedy** [CovidZero/covidzero-frontend#72]
Isso causa mais problemas no mobile. A altura do navbar não está sendo considerada e se tiver conteúdo que passa do navbar, ele acaba não mostrando o último elemento por completo como na imagem.

![image](https://user-images.githubusercontent.com/25750884/77444298-6abfd680-6dca-11ea-838e-451f64299e10.png)

**Comment by shindhi** [comment]
Fazendo.
