### ISSUE TITLE
Adequar página de notícia/item (web) ao aprovado 

### ISSUE THREAD

**Issue by Qnedy** [CovidZero/covidzero-frontend#73]
Atualmente está assim: 
![image](https://user-images.githubusercontent.com/25750884/77444859-1e28cb00-6dcb-11ea-94cb-1e54f6f0b312.png)

Design aprovado:
![image](https://user-images.githubusercontent.com/25750884/77444817-1406cc80-6dcb-11ea-84d9-ae91060ea601.png)

**Comment by breno-sapucaia** [comment]
Ficou legal? Quer que altera mais alguma coisa?

**Comment by MatheusBueno** [comment]
@breno-sapucaia fiz um revert no merge que tinah feito pois na versão mobile ficou diferente do proposto no layout

**Comment by MatheusBueno** [comment]
Resolvido no PR  #79
